-- Migration: initial schema for JumpFlix content
-- Generated from supabase/schema.sql

create table if not exists public.media_items (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    type text not null check (type in ('movie', 'series')),
    title text not null,
    description text,
    thumbnail text,
    blurhash text,
    paid boolean default false,
    provider text,
    external_url text,
    year text,
    duration text,
    video_id text,
    vimeo_id text,
    trakt text,
    creators text[] default '{}'::text[],
    starring text[] default '{}'::text[],
    video_count integer,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists media_items_type_idx on public.media_items (type);

create table if not exists public.series_seasons (
    id bigint generated by default as identity primary key,
    series_id bigint not null references public.media_items(id) on delete cascade,
    season_number integer not null,
    playlist_id text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique(series_id, season_number)
);

create table if not exists public.series_episodes (
    id bigint generated by default as identity primary key,
    season_id bigint not null references public.series_seasons(id) on delete cascade,
    episode_number integer not null,
    video_id text,
    title text,
    description text,
    published_at timestamptz,
    thumbnail text,
    duration text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique(season_id, episode_number),
    unique(season_id, video_id)
);

alter table public.media_items enable row level security;
alter table public.series_seasons enable row level security;
alter table public.series_episodes enable row level security;

create policy if not exists "Media items are readable" on public.media_items for select using (true);
create policy if not exists "Series seasons are readable" on public.series_seasons for select using (true);
create policy if not exists "Series episodes are readable" on public.series_episodes for select using (true);
