-- Migration: Add ratings table for user content ratings
-- Users can rate media items from 1-10 (Bangerometer)

create table if not exists public.ratings (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    media_id bigint not null references public.media_items(id) on delete cascade,
    rating integer not null check (rating >= 1 and rating <= 10),
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique(user_id, media_id)
);

-- Index for faster lookups
create index if not exists ratings_media_id_idx on public.ratings (media_id);
create index if not exists ratings_user_id_idx on public.ratings (user_id);

-- Enable RLS
alter table public.ratings enable row level security;

-- RLS Policies: Users can only view/manage their own ratings
create policy "Ratings are viewable by everyone" on public.ratings
    for select using (true);

create policy "Ratings are insertable by authenticated users" on public.ratings
    for insert with check ((select auth.uid()) = user_id);

create policy "Ratings are updatable by owner" on public.ratings
    for update using ((select auth.uid()) = user_id);

create policy "Ratings are deletable by owner" on public.ratings
    for delete using ((select auth.uid()) = user_id);

-- Create a view for average ratings per media item
create or replace view public.media_ratings_summary as
select 
    media_id,
    count(*) as rating_count,
    round(avg(rating)::numeric, 1) as average_rating
from public.ratings
group by media_id;

-- Grant access to the view
grant select on public.media_ratings_summary to anon, authenticated;
