-- Migration: Add reviews table for user-written reviews

create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    media_id bigint not null references public.media_items(id) on delete cascade,
    author_name text,
    body text not null check (char_length(body) between 1 and 2000),
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique(user_id, media_id)
);

create index if not exists reviews_media_id_idx on public.reviews (media_id);
create index if not exists reviews_user_id_idx on public.reviews (user_id);
create index if not exists reviews_created_at_idx on public.reviews (created_at desc);

alter table public.reviews enable row level security;

drop policy if exists "Reviews are viewable by everyone" on public.reviews;
create policy "Reviews are viewable by everyone" on public.reviews
    for select using (true);

drop policy if exists "Reviews are insertable by authenticated users" on public.reviews;
create policy "Reviews are insertable by authenticated users" on public.reviews
    for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Reviews are updatable by owner" on public.reviews;
create policy "Reviews are updatable by owner" on public.reviews
    for update using ((select auth.uid()) = user_id);

drop policy if exists "Reviews are deletable by owner" on public.reviews;
create policy "Reviews are deletable by owner" on public.reviews
    for delete using ((select auth.uid()) = user_id);

drop trigger if exists set_updated_at on public.reviews;
create trigger set_updated_at before update on public.reviews
    for each row
    execute function public.set_current_timestamp_updated_at();
