create table if not exists public.project_costs (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    vendor text not null,
    category text not null check (category in ('hosting', 'video', 'ai', 'developer-tools', 'database', 'other')),
    amount numeric(12, 2) not null check (amount >= 0),
    currency text not null default 'USD' check (char_length(currency) = 3),
    occurred_at timestamptz not null default now(),
    coverage text not null default 'direct' check (coverage in ('direct', 'sponsored', 'waived')),
    entry_method text not null default 'manual' check (entry_method in ('manual', 'api_import', 'seed')),
    source_system text,
    source_reference text,
    is_public boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists project_costs_public_occurred_idx on public.project_costs (is_public, occurred_at desc);
create index if not exists project_costs_vendor_idx on public.project_costs (vendor, occurred_at desc);
create index if not exists project_costs_category_idx on public.project_costs (category, occurred_at desc);

alter table public.project_costs enable row level security;

drop policy if exists "Project costs are readable" on public.project_costs;
create policy "Project costs are readable" on public.project_costs
    for select using (is_public = true);

grant select on table public.project_costs to anon, authenticated;

drop trigger if exists set_project_costs_updated_at on public.project_costs;
create trigger set_project_costs_updated_at before update on public.project_costs
    for each row
    execute function public.set_current_timestamp_updated_at();

create table if not exists public.project_donations (
    id bigint generated by default as identity primary key,
    supporter_name text,
    note text,
    amount numeric(12, 2) not null check (amount >= 0),
    currency text not null default 'USD' check (char_length(currency) = 3),
    donated_at timestamptz not null default now(),
    entry_method text not null default 'manual' check (entry_method in ('manual', 'api_import', 'seed')),
    source_system text,
    source_reference text,
    is_public boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists project_donations_public_donated_idx on public.project_donations (is_public, donated_at desc);
create index if not exists project_donations_supporter_idx on public.project_donations (supporter_name, donated_at desc);

alter table public.project_donations enable row level security;

drop policy if exists "Project donations are readable" on public.project_donations;
create policy "Project donations are readable" on public.project_donations
    for select using (is_public = true);

grant select on table public.project_donations to anon, authenticated;

drop trigger if exists set_project_donations_updated_at on public.project_donations;
create trigger set_project_donations_updated_at before update on public.project_donations
    for each row
    execute function public.set_current_timestamp_updated_at();
