-- Add user-submitted content suggestions + admin moderation

create table if not exists public.content_suggestions (
    id bigint generated by default as identity primary key,
    media_id bigint not null references public.media_items(id) on delete cascade,
    media_type text not null check (media_type in ('movie', 'series')),
    target_scope text not null default 'media' check (target_scope in ('media', 'episode')),
    season_number integer,
    episode_number integer,
    kind text not null,
    note text,
    payload jsonb not null default '{}'::jsonb,
    contact_email text,
    source_path text,
    status text not null default 'pending' check (status in ('pending', 'approved', 'declined')),
    admin_note text,
    admin_payload jsonb,
    processed_at timestamptz,
    processed_by uuid references auth.users(id) on delete set null,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint content_suggestions_episode_requires_season check (
        episode_number is null or season_number is not null
    )
);

create index if not exists content_suggestions_media_id_idx on public.content_suggestions (media_id);
create index if not exists content_suggestions_status_created_at_idx on public.content_suggestions (status, created_at desc);

alter table public.content_suggestions enable row level security;

-- Public can submit suggestions (anon + authenticated)
drop policy if exists "Content suggestions are insertable" on public.content_suggestions;
create policy "Content suggestions are insertable" on public.content_suggestions
  for insert
  with check (
    status = 'pending'
    and (created_by is null or created_by = auth.uid())
  );

-- Keep updated_at fresh
-- Re-use helper from watch_history migration: public.set_current_timestamp_updated_at()
drop trigger if exists set_content_suggestions_updated_at on public.content_suggestions;
create trigger set_content_suggestions_updated_at before update on public.content_suggestions
    for each row
    execute function public.set_current_timestamp_updated_at();

comment on table public.content_suggestions is 'User-submitted suggestions and issue reports for media items (movies and series), reviewed by admins.';
comment on column public.content_suggestions.kind is 'Suggestion category (e.g., new_episode, new_season, facets, poster, subscription, broken_link, tracks, other).';
comment on column public.content_suggestions.payload is 'Structured suggestion data as JSON (optional).';
